### PR TITLE
Adding descriptive docs

### PR DESCRIPTION
**Pull request by hannelita**
@jexp @ryguyrg What would be the best doc structure in your opinion?
Pure wiki would not be effective since it does nos allow PRs. We need something that allows community contributions.
What about having a directory here + a Wiki and add doc/ content to the Wiki page?
Or should we use Asciidoctor? (I can convert the syntax in this case)

### CODE REVIEW

**Comment by jexp** [comment]
Yes ascidoc would be best then we can integrate it easily with the website or even manual.

**Comment by hannelita** [comment]
Ok I'll change to asciidoc

**Comment by jexp** [comment]
Can you squash the 4 commits into one?

**Comment by jexp** [comment]
Rename "mappings", "mapping plan" to something consistent like mapping strategy.

We have to be clear about the target audience, for me it is users of this connector, so they couldn't care less about method signatures and internal implementation. What they care about are 

* configuration options
* how to setup and start this connector in few steps
* the different mapping strategies
* considerations we made when developing these strategies
* further plans

Try to format the JSON documents so that they are easy to read, shorten the long strings into using ellipsis "..."

best use code sections with language

```
[source,javascript]
====
{}
====
````

In AsciiDoc bold is one star, and italics is an underscore.

We also have to go over the documentation for language consistency and easy readability @ryguyrg

**Comment by hannelita** [comment]
@jexp squashed

**Comment by jexp** [comment]
Did you see my other comments regarding the long strings and the asciidoc syntax for code etc?

Also the url syntax is: `http://example.com[link text]`

You can see it if you "view" the rendered adoc in github, chrome asciidoc extension or atom preview pane.

**Comment by hannelita** [comment]
@jexp 'In AsciiDoc bold is one star, and italics is an underscore.'
Double star is supported as bold also :)

**Pull request merged**
